# Generated by Django 3.0.5 on 2020-04-11 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsSpecialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='VoltDoctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile_num', models.CharField(max_length=150)),
                ('from_time', models.CharField(max_length=50)),
                ('to_time', models.CharField(max_length=50)),
                ('from_per', models.CharField(choices=[('مساءًا', 'مساءًا'), ('صباحًا', 'صباحًا')], max_length=50)),
                ('to_per', models.CharField(choices=[('مساءًا', 'مساءًا'), ('صباحًا', 'صباحًا')], max_length=50)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors_app.DoctorsSpecialist')),
            ],
        ),
    ]
