# Generated by Django 3.0.5 on 2020-04-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_covidstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidstats',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
