# Generated by Django 3.0.5 on 2020-04-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200414_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidstats',
            name='new_confirmed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covidstats',
            name='new_deaths',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covidstats',
            name='new_recovered',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='covidstats',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
