# Generated by Django 3.0.5 on 2020-04-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200414_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidstats',
            name='counter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
