# Generated by Django 3.0.5 on 2020-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyPhones_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyphone',
            name='logo',
            field=models.URLField(default='http://127.0.0.1:8000/admin/'),
            preserve_default=False,
        ),
    ]
