# Generated by Django 3.0.5 on 2020-04-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyPhones_app', '0002_emergencyphone_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyphone',
            name='logo',
            field=models.ImageField(upload_to='images/emergency/'),
        ),
    ]
